spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  application:
    name: ${APPLICATION_NAME}
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      base-url: ${SPRING_AI_OPENAI_BASE_URL}
      chat:
        options:
          model: ${SPRING_AI_OPENAI_CHAT_OPTIONS_MODEL}
          temperature: ${SPRING_AI_OPENAI_CHAT_OPTIONS_TEMPERATURE}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /api

app:
  datasource:
    url: ${APP_DATASOURCE_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
    driver-class-name: ${APP_DATASOURCE_DRIVER_CLASS_NAME}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: ${APP_JPA_SHOW_SQL:true}
    format-sql: ${APP_JPA_FORMAT_SQL:true}
  jwt:
    secret: ${APP_JWT_SECRET}
  url:
    frontend: ${APP_URL_FRONTEND}
  webhook:
    url: ${APP_WEBHOOK_URL}
    api-key: ${WEBHOOK_API_KEY}

waha:
  api:
    url: ${WAHA_API_URL}
    key: ${WAHA_API_KEY}

