spring:
  application:
    name: ${APPLICATION_NAME:AppDespesas}
  ai:
    openai:
      api-key: ${AI_OPENAI_API_KEY}
      base-url: ${AI_OPENAI_BASE_URL}
      chat:
        options:
          model: ${AI_OPENAI_CHAT_OPTIONS_MODEL:llama-3.3-70b-versatile}
          temperature: ${AI_OPENAI_CHAT_OPTIONS_TEMPERATURE:0.3}
  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /api

app:
  datasource:
    url: ${APP_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${APP_DATASOURCE_USERNAME:postgres}
    password: ${APP_DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${APP_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: ${APP_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${APP_JPA_SHOW_SQL:true}
    format-sql: ${APP_JPA_FORMAT_SQL:true}
  jwt:
    secret: ${APP_JWT_SECRET}
  url:
    frontend: ${APP_URL_FRONTEND}
  webhook:
    api-key: ${APP_WEBHOOK_API_KEY}

waha:
  api:
    url: ${WAHA_API_URL}
    key: ${WAHA_API_KEY}

