spring:
  application:
    name: AppDespesas

server:
  servlet:
    context-path: /api

app:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    format-sql: true
  jwt:
    secret: kR9$F7pLx2A!mZQ4vE#N8JcW@D6sT%qH0B^aM1yUo5eCGrhKPiL
  url:
    frontend: http://localhost:3000
  webhook:
    api-key: ${WEBHOOK_API_KEY:wh_8F3kL9mN2pQ7rT1vY4xZ6aB0cD5eG8hJ}

waha:
  api:
    url: ${WAHA_API_URL:http://waha:3000}
    key: ${WAHA_API_KEY:0a506b5cef4643e6972a47579051fc6f}

