spring:
  application:
    name: AppDespesas
  ai:
    openai:
      api-key: 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
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.3
  jackson:
    deserialization:
      fail-on-unknown-properties: false

server:
  servlet:
    context-path: /api

app:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
    format-sql: true
  jwt:
    secret: 9P@rB7xF!mE2W^Tq5yKZ0D#H1J8L$A6cR%M4GQnCseUoipVYdOaXhI
  url:
    frontend: http://localhost:3000
  webhook:
    api-key: wh_8F3kL9mN2pQ7rT1vY4xZ6aB0cD5eG8hJ

waha:
  api:
    url: http://localhost:3001
    key: 0a506b5cef4643e6972a47579051fc6f

